name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - canary

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: heroui-runner
    timeout-minutes: 30
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/common-actions/install

      - name: Tests
        run: pnpm test

      - name: Build
        id: build
        continue-on-error: false
        # Custom turbo build failure information
        run: |
          pnpm build || {
            echo "Turbo build failed with exit code $?"
            exit 1
          }

      - name: Create Release Pull Request or Publish to NPM
        # Run only if the build is successful
        if: steps.build.outcome == 'success'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "ci(changesets): :package: version packages"
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create canary release
        if: steps.build.outcome == 'success' && steps.changesets.outputs.published != 'true'
        timeout-minutes: 15
        run: |
          git checkout canary
          pnpm version:canary
          pnpm release:canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
